### ISSUE TITLE
binding on element in list?

### ISSUE THREAD

**Issue by pachacamac** [mardix/relift-html#11]
Quick question. My template looks like this:

    <ul class="agenda">
      <li r-for="(point,i) in this.points">
        <h3>{point.topic}</h3>
        <input type="text" @bind="point.notes" value="{point.notes}">
        <a @click="remove" data-index="{i}">[x]</a>
    </ul>

and my data looks like this:

    data: {
      points: [
        {topic: 'Take dog to school', notes: ''},
        {topic: 'Eat dinner', notes: 'later'},
        {topic: 'Code more', notes: ''}
      ],
    },

How do I correctly bind the input boxes in the loop to the right point notes?

Thank you in advance! Awesome project :)

**Comment by pachacamac** [comment]
Found it out myself :)

`<input type="text" @bind="points.{i}.notes" value="{point.notes}">`

**Comment by mardix** [comment]
Good stuff. Thanks
