### ISSUE TITLE
jsfiddle Demo throws error

### ISSUE THREAD

**Issue by rusco** [mardix/relift-html#6]
Please check: https://jsfiddle.net/hdfup3cg/

I get this error in my Win10/Chrome73 console:

relift-html.esm.js:9 Uncaught SyntaxError: Identifier 't' has already been declared

**Comment by mardix** [comment]
The issue has been fixed. It happened that Rollup, during bundling, misnamed some variable. Had to implement a small work around to bypass that issue. it's good now.

Thanks

**Comment by rusco** [comment]
Unkpg still has  to syncronize, the original fiddle is not yet working, but manually pointing to 0.10.1 works.
Keep up the good job! 
BTW: Typescript would be nicer than Vanilla-Js !
